### ISSUE TITLE
key not found in "form[key]"  "api/modules/formatters.py" and server overload 

### ISSUE THREAD

**Issue by zpdeng** [calpoly-csai/api#77]
**Describe the bug**
When running Postman tests for "/new_data/wakeword" in `flask_api.py`, it encounters error where name key is not found for "form[key]'. Screenshot shows Postman tests and the results. 

(CODE REFERENCE )[https://github.com/calpoly-csai/api/blob/0d99d7ef62bb899d22ce721af9531c2ed661d9ac/modules/formatters.py#L22](url)
![image](https://user-images.githubusercontent.com/28467621/75526318-66b8b880-59c6-11ea-8dd8-35d769e1fc13.png)

Also encountered "Status 500 Server Overload" when running with Postman tests with "https://calpoly-csai-nimbus.herokuapp.com/..." url. 

![image](https://user-images.githubusercontent.com/28467621/75526499-c1eaab00-59c6-11ea-84eb-0ba0cf8d6b55.png)

**Comment by mfekadu** [comment]
@zpdeng i think the test is missing the `wav_file` which needs to be a binary type

Also make sure to send **form_data** instead of JSON

**Comment by mfekadu** [comment]
Furthermore, let’s share postman collections rather than screenshots

* https://youtu.be/mVTsK6ZdY6c
* https://www.guru99.com/postman-tutorial.html
* https://learning.postman.com/docs/postman/collaboration/collaboration-intro/
* https://medium.com/@peter.jp.xie/rest-api-testing-using-python-751022c364b8
